### ISSUE TITLE
Qovluq və fayl strukturu

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [RovsenRzali/PragmatechFoundationProject#1]
### <p align="center">Qovluq və fayl strukturu bu şəkildə olmalıdır.</p>
![Qovluq və fayl strukturu](https://user-images.githubusercontent.com/86655646/143594569-774a940f-590c-4f40-939c-161acc185d63.png)

**[Bu](https://github.com/PragmatechEducation/FoundationStudent)** və **[bu](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5)** qaynaqlardakı kimi olmalıdır hər şey. Qaynaqları yaxşıca analiz edin və tətbiq etməyə çalışın.

**Comment by RovsenRzali** [comment]
Həll edə bildimi?

**Comment by isbendiyarovanezrin** [comment]
Tam yox.

**Comment by RovsenRzali** [comment]
Hansı hissə qaldı?

**Comment by isbendiyarovanezrin** [comment]
Sizcə, sizdə hər şey 1-ci issue'dəki kimidir?

**Comment by RovsenRzali** [comment]
Xeir. 2ci "bu" sözündəki file və folder ləridə əlavə etdim.  olarıda 1ci "bu" sözündəki faylarla bir yerə əlavə etdim.  İndi oları necə düzəldim?

**Comment by isbendiyarovanezrin** [comment]
Onları "Works" qovluğunun içinə əlavə edin, çünki 1-ci "bu" sözündə olan linkdə elədir.

**Comment by RovsenRzali** [comment]
bu səfər həll edə bildimi?

**Comment by isbendiyarovanezrin** [comment]
Bəli.🙂
